### ISSUE TITLE
system design documentation link is not public

### ISSUE THREAD

**Issue by fsaintjacques** [tensorflow/mlir#1]
The rationale document [references](https://github.com/tensorflow/mlir/blame/master/g3doc/Rationale.md#L28) the system design documentation found at https://docs.google.com/document/d/1yRqja94Da6NtKmPxSYtTx6xbUtughLANyeD7dZ7mOBM/edit# which is not public.

**Comment by joker-eph** [comment]
Thanks for the bug report!

@lattner removed this link (and updated others) in ec7ba0c807b5558a64fb6a0e7cbd1bb213a04aa0.
This document is very outdated and has been superseded by others in here.
