### ISSUE TITLE
mlir::ExecutionEngine isn't using the opt pipeline

### ISSUE THREAD

**Issue by bondhugula** [tensorflow/mlir#120]
Although ExecutionEngine::create takes an optimizing pass pipeline as input, that argument ('transformer') remains unused --- a previous commit changed that and so its doc comment is inaccurate. As a result, code generated by 'mlir-cpu-runner -O3' for example  is vastly different than that by  '... | mlir-translate -mlir-to-llvmir | opt -O3  | llc -O3'. 
This impacts both mlir-cpu-runner and the toy example language (examples/toy/Ch5/toyc.cpp).

https://github.com/tensorflow/mlir/blob/cf461e226780d05792573578fb7a01cddb8469be/lib/ExecutionEngine/ExecutionEngine.cpp#L196

**Comment by nicolasvasilache** [comment]
thanks for your report, sending a fix soon.

**Comment by bondhugula** [comment]
@nicolasvasilache  Thanks for the quick fix! While this runs the opt O3 passes, the right/specified optimization level would still not be used for the actual machine code generation  - sort of like using -O3 with 'opt' but using no opt with 'llc'. (It can impact performance significantly.) I"ll send a fix for this.
