### ISSUE TITLE
ExecutionEngine debug messages in release mode

### ISSUE THREAD

**Issue by nmostafa** [tensorflow/mlir#125]
@nicolasvasilache , 
In https://github.com/tensorflow/mlir/blob/72e261bae4f48eb513cee6f7ffea5ecd0c90458b/lib/ExecutionEngine/ExecutionEngine.cpp#L80

Are you missing LLVM_DEBUG(..) or is this intentional ? It is polluting our output currently for nGraph unit-tests. I think it should be enabled only debug build with `-debug ` flag.

**Comment by joker-eph** [comment]
Fixed in f48ab96e78715390c3f79cb9ff74b80e23897f25

**Comment by nicolasvasilache** [comment]
Thanks for the fix!
