### ISSUE TITLE
[spirv] Add OpControlBarrier and OpMemoryBarrier

### ISSUE THREAD

**Issue by antiagainst** [tensorflow/mlir#127]
We need the definitions of these two ops and their (de)serialization.

**Comment by antiagainst** [comment]
@denis0x0D are you willing to help on this? :)

**Comment by denis0x0D** [comment]
@antiagainst yes, of course! Thanks a lot!

**Comment by antiagainst** [comment]
This is done via #130. Thanks @denis0x0D!
