### ISSUE TITLE
WASI

### ISSUE THREAD

**Issue by bhack** [tensorflow/mlir#140]
Is there any Plan to have an interaction with WASI:
https://github.com/WebAssembly/WASI/issues/59 ?

**Comment by bhack** [comment]
Check also https://github.com/WebAssembly/WASI/issues/53

**Comment by joker-eph** [comment]
I'm not aware of any plan with respect to WASI, but if there are concrete and specific things we can do or collaborate on, we would be happy too.

**Comment by bhack** [comment]
I think some Google employee was at the Berlin meeting mentioning MLIR:

https://github.com/webmachinelearning/meetings/blob/master/2019-09-17-fukuoka/README.md#meeting-minutes

**Comment by bhack** [comment]
@nsthorat Do you was there?

**Comment by nsthorat** [comment]
@bhack I was there and presented MLIR -- this is nothing concrete just an FYI about MLIR for the group. However, WASM is a backend for LLVM so presumably MLIR can target WASM through LLVM.

**Comment by bhack** [comment]
@nsthorat Yes I saw you slides. My question was most related as Tensorflow it is entering in the WASM domain with https://github.com/tensorflow/tfjs/issues/1497#issuecomment-528944014 I suppose that in the WASI context, that it is more in an early stage, the MLIR team really wants to play some more "design" role in this phase.
It is why I have mentioned that specific AI/ML WASI issue in this ticket description.

**Comment by bhack** [comment]
@nsthorat Seems that llvm [libc++ 9.0](https://releases.llvm.org/9.0.0/projects/libcxx/docs/ReleaseNotes.html#updates) added explicit support for WASI:
> libc++ added explicit support for WebAssembly System Interface (WASI).

**Comment by bhack** [comment]
Some related news:
https://hacks.mozilla.org/2019/11/announcing-the-bytecode-alliance/

**Comment by bhack** [comment]
There will be W3C conference in Berlin on March 2020. @nsthorat is in the committee:
https://www.w3.org/2020/01/machine-learning-workshop/
