### ISSUE TITLE
linalg-execution-3 seems broken in Windows VS 2017 Debug

### ISSUE THREAD

**Issue by liwchang** [tensorflow/mlir#164]
Windows, VS 2017

JITSymbolFlag mismatched in ExecutionEngine/Orc/Core.cpp (Line 388)
Release might have the same issue, but just that assert is optimized. 

BTW, by default, linalg-execution-3 won't be built using the instructions in Getting started with MLIR. That is probably the reason it didn't get caught.

**Comment by joker-eph** [comment]
We're retiring this code soon (as in deleting it from the repository), likely in the next two weeks.

**Comment by liwchang** [comment]
Wow. Good to know, thanks @joker-eph. Will there be something similar to LinAlg in the updated tutorial?

**Comment by joker-eph** [comment]
Not exactly like Linalg, we'll lower to affine instead I think. What is it that you're looking for exactly?
We will have this ready by the end of the week if everything goes well.

There is a full-fledge Linalg dialect in the repo now, outside of the "example". It is confusing to have the two in-tree and the tutorial-linalg isn't really maintained. Instead we may add a late chapter in the tutorial about how to use linalg, but I suspect this will be something to be done ~ 6 months from now (linalg itself is still evolving quite fast).

**Comment by River707** [comment]
The Linalg tutorial has been removed. Closing this now.
