### ISSUE TITLE
Failing test with optimized build

### ISSUE THREAD

**Issue by bondhugula** [tensorflow/mlir#17]
With an optimized build

$ cmake -G Ninja ../llvm -DLLVM_BUILD_EXAMPLES=ON -DCMAKE_BUILD_TYPE=Release

I see one failing test case.

$ ninja check-mlir
...
[  FAILED  ] 1 test, listed below:
[  FAILED  ] DialectDeathTest.MultipleDialectsWithSameNamespace

 1 FAILED TEST

********************
Testing Time: 0.81s
********************
Failing Tests (1):
    MLIR-Unit :: IR/./MLIRIRTests/DialectDeathTest.MultipleDialectsWithSameNamespace

  Expected Passes    : 98
  Unexpected Failures: 1
FAILED: projects/mlir/test/CMakeFiles/check-mlir 
cd /home/uday/git/llvm-project/build_opt/projects/mlir/test && /usr/bin/python2.7 /home/uday/git/llvm-project/build_opt/./bin/llvm-lit -sv /home/uday/git/llvm-project/build_opt/projects/mlir/test
ninja: build stopped: subcommand failed.
[uday@ukr-x1-laptop ~/git/llvm-project/build_opt]₹ ^C
[uday@ukr-x1-laptop ~/git/llvm-project/build_opt]₹ cmake -G Ninja ../llvm -DLLVM_BUILD_EXAMPLES=ON -DCMAKE_BUILD_TYPE=Release^C
[uday@ukr-x1-laptop ~/git/llvm-project/build_opt]₹ ninja check-mlir
[0/1] Running the MLIR regression tests
FAIL: MLIR-Unit :: IR/./MLIRIRTests/DialectDeathTest.MultipleDialectsWithSameNamespace (10 of 99)
******************** TEST 'MLIR-Unit :: IR/./MLIRIRTests/DialectDeathTest.MultipleDialectsWithSameNamespace' FAILED ********************
Note: Google Test filter = DialectDeathTest.MultipleDialectsWithSameNamespace
[==========] Running 1 test from 1 test case.
[----------] Global test environment set-up.
[----------] 1 test from DialectDeathTest
[ RUN      ] DialectDeathTest.MultipleDialectsWithSameNamespace
/home/uday/git/llvm-project/llvm/projects/mlir/unittests/IR/DialectTest.cpp:35: Failure
Death test: new TestDialect(&context)
    Result: failed to die.
 Error msg:
[  DEATH   ] 
[  FAILED  ] DialectDeathTest.MultipleDialectsWithSameNamespace (0 ms)
[----------] 1 test from DialectDeathTest (0 ms total)

[----------] Global test environment tear-down
[==========] 1 test from 1 test case ran. (1 ms total)
[  PASSED  ] 0 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] DialectDeathTest.MultipleDialectsWithSameNamespace

 1 FAILED TEST

********************
Testing Time: 0.81s
********************
Failing Tests (1):
    MLIR-Unit :: IR/./MLIRIRTests/DialectDeathTest.MultipleDialectsWithSameNamespace

  Expected Passes    : 98
  Unexpected Failures: 1
FAILED: projects/mlir/test/CMakeFiles/check-mlir 
cd /home/uday/git/llvm-project/build_opt/projects/mlir/test && /usr/bin/python2.7 /home/uday/git/llvm-project/build_opt/./bin/llvm-lit -sv /home/uday/git/llvm-project/build_opt/projects/mlir/test
ninja: build stopped: subcommand failed.

**Comment by joker-eph** [comment]
`Result: failed to die.`

Ah that's a good problem to have ;)

Joke aside, thanks for the report! We'll look into this after the conference.
