### ISSUE TITLE
Build Failure

### ISSUE THREAD

**Issue by nileshiith** [tensorflow/mlir#195]
Compilation fails on cloning and building the latest repo. Can you please help?

Thanks
-----------------------------------
cmake --build . --target check-mlir
[0/1] Re-running CMake...
-- Could NOT find Z3: Found unsuitable version "0.0.0", but required is at least "4.7.1" (found Z3_LIBRARIES-NOTFOUND)
-- Native target architecture is X86
-- Threads enabled.
-- Doxygen disabled.
-- Go bindings disabled.
-- Ninja version: 1.8.2
-- Could NOT find OCaml (missing: OCAMLFIND OCAML_VERSION OCAML_STDLIB_PATH) 
-- Could NOT find OCaml (missing: OCAMLFIND OCAML_VERSION OCAML_STDLIB_PATH) 
-- OCaml bindings disabled.
-- LLVM host triple: x86_64-unknown-linux-gnu
-- LLVM default target triple: x86_64-unknown-linux-gnu
-- Building with -fPIC
-- Constructing LLVMBuild project information
-- Linker detection: GNU ld
-- Targeting X86
-- Failed to find LLVM FileCheck
-- Version: 0.0.0
-- Performing Test HAVE_GNU_POSIX_REGEX -- failed to compile
-- Performing Test HAVE_POSIX_REGEX -- success
-- Performing Test HAVE_STEADY_CLOCK -- success
-- Configuring done
-- Generating done
-- Build files have been written to: /home/nilesh/llvm-project/mlir-build
[36/381] Building CXX object lib/Target/X86/CMakeFiles/LLVMX86CodeGen.dir/X86ISelDAGToDAG.cpp.o
In file included from /home/nilesh/llvm-project/llvm/lib/Target/X86/X86ISelDAGToDAG.cpp:206:
lib/Target/X86/X86GenDAGISel.inc: In member function ‘virtual bool {anonymous}::X86DAGToDAGISel::CheckNodePredicate(llvm::SDNode*, unsigned int) const’:
lib/Target/X86/X86GenDAGISel.inc:266882: note: -Wmisleading-indentation is disabled from this point onwards, since column-tracking was disabled due to the size of the code/headers
 return true;
 
[179/381] Building CXX object projects/mlir/lib/ExecutionEngine/CMakeFiles/MLIRExecutionEngine.dir/ExecutionEngine.cpp.o
FAILED: projects/mlir/lib/ExecutionEngine/CMakeFiles/MLIRExecutionEngine.dir/ExecutionEngine.cpp.o 
/usr/bin/c++  -DGTEST_HAS_RTTI=0 -D_DEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Iprojects/mlir/lib/ExecutionEngine -I/home/nilesh/llvm-project/llvm/projects/mlir/lib/ExecutionEngine -I/usr/include/libxml2 -Iinclude -I/home/nilesh/llvm-project/llvm/include -I/home/nilesh/llvm-project/llvm/projects/mlir/include -Iprojects/mlir/include -fPIC -fvisibility-inlines-hidden -Werror=date-time -std=c++14 -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-class-memaccess -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wno-comment -fdiagnostics-color -g    -fno-exceptions -fno-rtti -MD -MT projects/mlir/lib/ExecutionEngine/CMakeFiles/MLIRExecutionEngine.dir/ExecutionEngine.cpp.o -MF projects/mlir/lib/ExecutionEngine/CMakeFiles/MLIRExecutionEngine.dir/ExecutionEngine.cpp.o.d -o projects/mlir/lib/ExecutionEngine/CMakeFiles/MLIRExecutionEngine.dir/ExecutionEngine.cpp.o -c /home/nilesh/llvm-project/llvm/projects/mlir/lib/ExecutionEngine/ExecutionEngine.cpp
/home/nilesh/llvm-project/llvm/projects/mlir/lib/ExecutionEngine/ExecutionEngine.cpp: In lambda function:
/home/nilesh/llvm-project/llvm/projects/mlir/lib/ExecutionEngine/ExecutionEngine.cpp:239:31: error: ‘class llvm::orc::JITDylib’ has no member named ‘addGenerator’; did you mean ‘setGenerator’?
     session.getMainJITDylib().addGenerator(
                               ^~~~~~~~~~~~
                               setGenerator
/home/nilesh/llvm-project/llvm/projects/mlir/lib/ExecutionEngine/ExecutionEngine.cpp:257:10: error: ‘class llvm::orc::JITDylib’ has no member named ‘addGenerator’; did you mean ‘setGenerator’?
       JD.addGenerator(std::move(*loaded));
          ^~~~~~~~~~~~
          setGenerator
/home/nilesh/llvm-project/llvm/projects/mlir/lib/ExecutionEngine/ExecutionEngine.cpp: In static member function ‘static llvm::Expected<std::unique_ptr<mlir::ExecutionEngine> > mlir::ExecutionEngine::create(mlir::ModuleOp, std::function<llvm::Error(llvm::Module*)>, llvm::Optional<llvm::CodeGenOpt::Level>, llvm::ArrayRef<llvm::StringRef>, bool)’:
/home/nilesh/llvm-project/llvm/projects/mlir/lib/ExecutionEngine/ExecutionEngine.cpp:281:75: error: no matching function for call to ‘llvm::orc::LLJITBuilder::setObjectLinkingLayerCreator(mlir::ExecutionEngine::create(mlir::ModuleOp, std::function<llvm::Error(llvm::Module*)>, llvm::Optional<llvm::CodeGenOpt::Level>, llvm::ArrayRef<llvm::StringRef>, bool)::<lambda(llvm::orc::ExecutionSession&, const llvm::Triple&)>&)’
                    .setObjectLinkingLayerCreator(objectLinkingLayerCreator)
                                                                           ^
In file included from /home/nilesh/llvm-project/llvm/projects/mlir/include/mlir/ExecutionEngine/ExecutionEngine.h:27,
                 from /home/nilesh/llvm-project/llvm/projects/mlir/lib/ExecutionEngine/ExecutionEngine.cpp:22:
/home/nilesh/llvm-project/llvm/include/llvm/ExecutionEngine/Orc/LLJIT.h:226:15: note: candidate: ‘SetterImpl& llvm::orc::LLJITBuilderSetters< <template-parameter-1-1>, <template-parameter-1-2>, <template-parameter-1-3> >::setObjectLinkingLayerCreator(llvm::orc::LLJITBuilderState::ObjectLinkingLayerCreator) [with JITType = llvm::orc::LLJIT; SetterImpl = llvm::orc::LLJITBuilder; State = llvm::orc::LLJITBuilderState; llvm::orc::LLJITBuilderState::ObjectLinkingLayerCreator = std::function<std::unique_ptr<llvm::orc::ObjectLayer>(llvm::orc::ExecutionSession&)>]’
   SetterImpl &setObjectLinkingLayerCreator(
               ^~~~~~~~~~~~~~~~~~~~~~~~~~~~
/home/nilesh/llvm-project/llvm/include/llvm/ExecutionEngine/Orc/LLJIT.h:226:15: note:   no known conversion for argument 1 from ‘mlir::ExecutionEngine::create(mlir::ModuleOp, std::function<llvm::Error(llvm::Module*)>, llvm::Optional<llvm::CodeGenOpt::Level>, llvm::ArrayRef<llvm::StringRef>, bool)::<lambda(llvm::orc::ExecutionSession&, const llvm::Triple&)>’ to ‘llvm::orc::LLJITBuilderState::ObjectLinkingLayerCreator’ {aka ‘std::function<std::unique_ptr<llvm::orc::ObjectLayer>(llvm::orc::ExecutionSession&)>’}
/home/nilesh/llvm-project/llvm/projects/mlir/lib/ExecutionEngine/ExecutionEngine.cpp:279:7: error: ‘cantFail’ was not declared in this scope
       cantFail(llvm::orc::LLJITBuilder()
       ^~~~~~~~
/home/nilesh/llvm-project/llvm/projects/mlir/lib/ExecutionEngine/ExecutionEngine.cpp:279:7: note: suggested alternative:
In file included from /home/nilesh/llvm-project/llvm/include/llvm/Support/FileSystem.h:34,
                 from /home/nilesh/llvm-project/llvm/include/llvm/Support/MemoryBuffer.h:22,
                 from /home/nilesh/llvm-project/llvm/include/llvm/ExecutionEngine/ObjectCache.h:12,
                 from /home/nilesh/llvm-project/llvm/projects/mlir/include/mlir/ExecutionEngine/ExecutionEngine.h:26,
                 from /home/nilesh/llvm-project/llvm/projects/mlir/lib/ExecutionEngine/ExecutionEngine.cpp:22:
/home/nilesh/llvm-project/llvm/include/llvm/Support/Error.h:749:4: note:   ‘llvm::cantFail’
 T& cantFail(Expected<T&> ValOrErr, const char *Msg = nullptr) {
    ^~~~~~~~
/home/nilesh/llvm-project/llvm/projects/mlir/lib/ExecutionEngine/ExecutionEngine.cpp:287:18: error: ‘class llvm::orc::ThreadSafeModule’ has no member named ‘withModuleDo’; did you mean ‘getModule’?
     cantFail(tsm.withModuleDo(
                  ^~~~~~~~~~~~
                  getModule
[186/381] Building CXX object projects/mlir/lib/Pass/CMakeFiles/MLIRPass.dir/PassRegistry.cpp.o
FAILED: projects/mlir/lib/Pass/CMakeFiles/MLIRPass.dir/PassRegistry.cpp.o 
/usr/bin/c++  -DGTEST_HAS_RTTI=0 -D_DEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Iprojects/mlir/lib/Pass -I/home/nilesh/llvm-project/llvm/projects/mlir/lib/Pass -I/usr/include/libxml2 -Iinclude -I/home/nilesh/llvm-project/llvm/include -I/home/nilesh/llvm-project/llvm/projects/mlir/include -Iprojects/mlir/include -fPIC -fvisibility-inlines-hidden -Werror=date-time -std=c++14 -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-class-memaccess -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wno-comment -fdiagnostics-color -g    -fno-exceptions -fno-rtti -MD -MT projects/mlir/lib/Pass/CMakeFiles/MLIRPass.dir/PassRegistry.cpp.o -MF projects/mlir/lib/Pass/CMakeFiles/MLIRPass.dir/PassRegistry.cpp.o.d -o projects/mlir/lib/Pass/CMakeFiles/MLIRPass.dir/PassRegistry.cpp.o -c /home/nilesh/llvm-project/llvm/projects/mlir/lib/Pass/PassRegistry.cpp
/home/nilesh/llvm-project/llvm/projects/mlir/lib/Pass/PassRegistry.cpp: In member function ‘mlir::LogicalResult mlir::detail::PassOptionsBase::parseFromString(llvm::StringRef)’:
/home/nilesh/llvm-project/llvm/projects/mlir/lib/Pass/PassRegistry.cpp:115:19: error: ‘ProvidePositionalOption’ is not a member of ‘llvm::cl’
     if (llvm::cl::ProvidePositionalOption(it->second, value, 0))
                   ^~~~~~~~~~~~~~~~~~~~~~~
[192/381] Building CXX object projects/mlir/lib/IR/CMakeFiles/MLIRIR.dir/MLIRContext.cpp.o
ninja: build stopped: subcommand failed.

**Comment by bondhugula** [comment]
Your LLVM commit ID? I think your LLVM copy might be behind the trunk. LLVM commit id 52bfa73af841bbbcee0ea59577c9d7b4bd9831d5 should work for example.

**Comment by nileshiith** [comment]
Thanks! it successfully build now.
