### ISSUE TITLE
Build error on macOS 

### ISSUE THREAD

**Issue by lucaciciriello** [tensorflow/mlir#207]
I got the following error:

fatal error: 'mlir/Analysis/CallInterfaces.h.inc' file not found

I'm building on macOS Catalina

In the attachment the complete reported error:
<img width="1676" alt="Screenshot 2019-10-23 at 17 04 32" src="https://user-images.githubusercontent.com/40060530/67407135-58413700-f5b7-11e9-83b9-9525edd884e4.png">

**Comment by joker-eph** [comment]
Fixed in 1702105f97a4d9ea35d767b6fbd73f627172b801
