### ISSUE TITLE
Toyc examples segfault on OS X when file not found

### ISSUE THREAD

**Issue by aaronsm** [tensorflow/mlir#229]
I just cloned all the necessary git repos and tried the toy tutorial on OS X. It's easy to make the examples segfault when the file is not found.

[toyc-ch2/ch3/ch4/ch5]
$ ./toyc-ch2 -emit=mlir foo
Could not open input file: No such file or directory
Segmentation fault: 11

[toyc-ch6/ch7]
$ ./toyc-ch6 foo
Could not open input file: No such file or directory
Segmentation fault: 11

**Comment by joker-eph** [comment]
Thanks for the report, this should be fixed now!
