### ISSUE TITLE
Build failure: llvm::orc API mismatch?

### ISSUE THREAD

**Issue by bondhugula** [tensorflow/mlir#24]
With the latest versions (commit IDs below), I see the appended build failure.

cmake flags
$ cmake -G Ninja ../llvm -DLLVM_BUILD_EXAMPLES=ON -DLLVM_ENABLE_CXX1Y=Y -DLLVM_TARGETS_TO_BUILD="host" -DCMAKE_BUILD_TYPE=Release

LLVM commit ID:
commit 63db7e347befefb87aaa02d33371d9b085ff2c3a (HEAD -> master, origin/master, origin/HEAD)
Author: Craig Topper <craig.topper@intel.com>
Date:   Sun Apr 21 05:18:04 2019 +0000

    [X86] Don't form masked vfpclass instruction from and+vfpclass unless the fpclass only has a single use.
    
    llvm-svn: 358841

MLIR commit ID

commit 0f1153870f96c9cc9465b475c0b3cd647fb66f13 (HEAD -> master, origin/master, origin/HEAD)
Author: Nicolas Vasilache <ntv@google.com>
Date:   Thu Apr 18 08:25:54 2019 -0700

        Start a Linalg dialect

[13/111] Building CXX object projects/mlir/lib/ExecutionEngine/CMakeFiles/MLIRExecutionEngine.dir/ExecutionEngine.cpp.o
FAILED: projects/mlir/lib/ExecutionEngine/CMakeFiles/MLIRExecutionEngine.dir/ExecutionEngine.cpp.o 
/usr/bin/c++  -DGTEST_HAS_RTTI=0 -D_DEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Iprojects/mlir/lib/ExecutionEngine -I/home/uday/git/llvm-project/llvm/projects/mlir/lib/ExecutionEngine -Iinclude -I/home/uday/git/llvm-project/llvm/include -I/home/uday/git/llvm-project/llvm/projects/mlir/include -Iprojects/mlir/include -fPIC -fvisibility-inlines-hidden -Werror=date-time -std=c++11 -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-class-memaccess -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wno-comment -fdiagnostics-color -ffunction-sections -fdata-sections -O2    -UNDEBUG  -fno-exceptions -fno-rtti -std=c++11 -MD -MT projects/mlir/lib/ExecutionEngine/CMakeFiles/MLIRExecutionEngine.dir/ExecutionEngine.cpp.o -MF projects/mlir/lib/ExecutionEngine/CMakeFiles/MLIRExecutionEngine.dir/ExecutionEngine.cpp.o.d -o projects/mlir/lib/ExecutionEngine/CMakeFiles/MLIRExecutionEngine.dir/ExecutionEngine.cpp.o -c /home/uday/git/llvm-project/llvm/projects/mlir/lib/ExecutionEngine/ExecutionEngine.cpp
/home/uday/git/llvm-project/llvm/projects/mlir/lib/ExecutionEngine/ExecutionEngine.cpp: In constructor ‘mlir::impl::OrcJIT::OrcJIT(llvm::orc::JITTargetMachineBuilder, llvm::DataLayout, mlir::impl::OrcJIT::IRTransformer)’:
/home/uday/git/llvm-project/llvm/projects/mlir/lib/ExecutionEngine/ExecutionEngine.cpp:101:19: error: no matching function for call to ‘llvm::orc::DynamicLibrarySearchGenerator::GetForCurrentProcess(llvm::DataLayout&)’
             layout)));
                   ^
In file included from /home/uday/git/llvm-project/llvm/projects/mlir/lib/ExecutionEngine/ExecutionEngine.cpp:32:
/home/uday/git/llvm-project/llvm/include/llvm/ExecutionEngine/Orc/ExecutionUtils.h:237:3: note: candidate: ‘static llvm::Expected<llvm::orc::DynamicLibrarySearchGenerator> llvm::orc::DynamicLibrarySearchGenerator::GetForCurrentProcess(char, llvm::orc::DynamicLibrarySearchGenerator::SymbolPredicate)’
   GetForCurrentProcess(char GlobalPrefix,
   ^~~~~~~~~~~~~~~~~~~~
/home/uday/git/llvm-project/llvm/include/llvm/ExecutionEngine/Orc/ExecutionUtils.h:237:3: note:   no known conversion for argument 1 from ‘llvm::DataLayout’ to ‘char’
/home/uday/git/llvm-project/llvm/projects/mlir/lib/ExecutionEngine/ExecutionEngine.cpp:100:9: error: ‘cantFail’ was not declared in this scope
         cantFail(llvm::orc::DynamicLibrarySearchGenerator::GetForCurrentProcess(
         ^~~~~~~~
/home/uday/git/llvm-project/llvm/projects/mlir/lib/ExecutionEngine/ExecutionEngine.cpp:100:9: note: suggested alternative:
In file included from /home/uday/git/llvm-project/llvm/projects/mlir/include/mlir/ExecutionEngine/ExecutionEngine.h:27,
                 from /home/uday/git/llvm-project/llvm/projects/mlir/lib/ExecutionEngine/ExecutionEngine.cpp:22:
/home/uday/git/llvm-project/llvm/include/llvm/Support/Error.h:749:4: note:   ‘llvm::cantFail’
 T& cantFail(Expected<T&> ValOrErr, const char *Msg = nullptr) {

**Comment by WLeeeee** [comment]
In file ExecutionEngine.cpp
You can fix it by changing
cantFail(llvm::orc::DynamicLibrarySearchGenerator::GetForCurrentProcess(layout)));

to

cantFail(llvm::orc::DynamicLibrarySearchGenerator::GetForCurrentProcess(layout.getGlobalPrefix())));

**Comment by bondhugula** [comment]
> In file ExecutionEngine.cpp
> You can fix it by changing
> cantFail(llvm::orc::DynamicLibrarySearchGenerator::GetForCurrentProcess(layout)));
> 
> to
> 
> cantFail(llvm::orc::DynamicLibrarySearchGenerator::GetForCurrentProcess(layout.getGlobalPrefix())));

Thanks. It builds with this change.

**Comment by joker-eph** [comment]
Fixed in c06365083b522da9fbda4eb174f166e490a1a557
