### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by lucaciciriello** [tensorflow/mlir#258]
On macOS Catalina (Xcode 11.2.1), I got the following error:

[1511/2284] Building CXX object projects/mlir/lib/Target/CMakeFiles/MLIRTargetLLVMIR.dir/LLVMIR/ConvertFromLLVMIR.cpp.o
FAILED: projects/mlir/lib/Target/CMakeFiles/MLIRTargetLLVMIR.dir/LLVMIR/ConvertFromLLVMIR.cpp.o 
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/c++  -DBUILD_EXAMPLES -DGTEST_HAS_RTTI=0 -D_DEBUG -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Iprojects/mlir/lib/Target -I/Users/luca.ciciriello/MLIR/llvm-project/llvm/projects/mlir/lib/Target -I/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk/usr/include/libxml2 -Iinclude -I/Users/luca.ciciriello/MLIR/llvm-project/llvm/include -I/Users/luca.ciciriello/MLIR/llvm-project/llvm/projects/mlir/include -Iprojects/mlir/include -fPIC -fvisibility-inlines-hidden -Werror=date-time -Werror=unguarded-availability-new -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wmissing-field-initializers -pedantic -Wno-long-long -Wimplicit-fallthrough -Wcovered-switch-default -Wno-noexcept-type -Wnon-virtual-dtor -Wdelete-non-virtual-dtor -Wstring-conversion -fdiagnostics-color -g -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.15.sdk    -fno-exceptions -fno-rtti -std=c++14 -MD -MT projects/mlir/lib/Target/CMakeFiles/MLIRTargetLLVMIR.dir/LLVMIR/ConvertFromLLVMIR.cpp.o -MF projects/mlir/lib/Target/CMakeFiles/MLIRTargetLLVMIR.dir/LLVMIR/ConvertFromLLVMIR.cpp.o.d -o projects/mlir/lib/Target/CMakeFiles/MLIRTargetLLVMIR.dir/LLVMIR/ConvertFromLLVMIR.cpp.o -c /Users/luca.ciciriello/MLIR/llvm-project/llvm/projects/mlir/lib/Target/LLVMIR/ConvertFromLLVMIR.cpp
In file included from /Users/luca.ciciriello/MLIR/llvm-project/llvm/projects/mlir/lib/Target/LLVMIR/ConvertFromLLVMIR.cpp:22:
In file included from /Users/luca.ciciriello/MLIR/llvm-project/llvm/projects/mlir/include/mlir/Dialect/LLVMIR/LLVMDialect.h:29:
/Users/luca.ciciriello/MLIR/llvm-project/llvm/projects/mlir/include/mlir/IR/OpImplementation.h:639:10: fatal error: 'mlir/IR/OpAsmInterface.h.inc' file not found
#include "mlir/IR/OpAsmInterface.h.inc"
         ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
1 error generated.

This error is presented when the following modules are building:

projects/mlir/lib/Target/CMakeFiles/MLIRTargetLLVMIR.dir/LLVMIR/ConvertFromLLVMIR.cpp.o
projects/mlir/lib/Dialect/LLVMIR/CMakeFiles/MLIRROCDLIR.dir/IR/ROCDLDialect.cpp.o
projects/mlir/lib/Dialect/LLVMIR/CMakeFiles/MLIRNVVMIR.dir/IR/NVVMDialect.cpp.o
projects/mlir/lib/Dialect/LLVMIR/CMakeFiles/MLIRLLVMIR.dir/IR/LLVMDialect.cpp.o
projects/mlir/lib/Target/CMakeFiles/MLIRTargetLLVMIRModuleTranslation.dir/LLVMIR/ModuleTranslation.cpp.o

**Comment by joker-eph** [comment]
Seems fixed with recent changes in our CMake dependence tree, let me know if you still see it

**Comment by lucaciciriello** [comment]
Yes, I confirm that this issue has been fixed
