### ISSUE TITLE
[Linalg] Add a Linalg iterator permutation transformation.

### ISSUE THREAD

**Issue by nicolasvasilache** [tensorflow/mlir#272]
Once #270 is landed, we can add a standalone iterator permutation transformation to Linalg.

This transformation should be very simple to write and should just compose a permutation map the with the maps in the "indexing_maps" attribute.

There is a C++ component and a Tablegen component (to make the transformation into a pattern) to this PR.

**Comment by tetuante** [comment]
Working on it!

**Comment by nicolasvasilache** [comment]
Done.
