### ISSUE TITLE
Visual Studio compilation failure

### ISSUE THREAD

**Issue by Meinersbur** [tensorflow/mlir#31]
Current master fails to compile with Visual Studio 2017 and 2019:
```
C:\Users\meinersbur\src\llvm\projects\mlir\include\mlir/IR/OpDefinition.h(740): error C2976: 'mlir::typelist_contains': too few template arguments
C:\Users\meinersbur\src\llvm\projects\mlir\include\mlir/IR/OpDefinition.h(44): note: see declaration of 'mlir::typelist_contains'
projects\mlir\include\mlir/StandardOps/Ops.h.inc(442): note: see reference to class template instantiation 'mlir::Op<mlir::ConstantOp,mlir::OpTrait::OneResult,mlir::OpTrait::HasNoSideEffect,mlir::OpTrait::NOperands<0>::Impl>' being compiled
```

This might be a compiler bug as it compiles with gcc and clang. Smaller reproducer:
```
template <typename ConcreteType>
class MyTrait {};

template<bool B>
class MyBool {};

class MyUsing {
public:
  template <typename ConcreteType>
  using Impl = MyTrait<ConcreteType>;
};

template <typename ConcreteType, template <typename T> class... Traits>
class Test {
  MyBool<typelist_contains<int, Traits<ConcreteType>...>::value> Y;
};

class MyTest : Test<MyTest, MyUsing::Impl> {
} T;
```

**Comment by joker-eph** [comment]
Can you double check if you see still the error? Our internal Windows CI is passing right now.

**Comment by Meinersbur** [comment]
The error as described has disappeared in 7eb515. However, using Visual Studio 2019 it still fails compiling with the following error:
```
C:\Users\meinersbur\src\llvm\projects\mlir\include\mlir/TableGen/Predicate.h(57,8): error C2039:  'string': is not a member of 'std'
```
This might due to the assumption that `<vector>` would implicitly include `<string>`. It does compile using gcc and Visual Studio 2017.

**Comment by joker-eph** [comment]
I added the include, please re-open if it still fails!

**Comment by Meinersbur** [comment]
In 6a9862, I get the 'too few template arguments' error again (VS 2017 and 2019):
```
C:\Users\meinersbur\src\llvm\projects\mlir\include\mlir/IR/OpDefinition.h(759): error C2976: 'mlir::FoldingHook': too few template arguments
C:\Users\meinersbur\src\llvm\projects\mlir\include\mlir/IR/OpDefinition.h(176): note: see declaration of 'mlir::FoldingHook'
projects\mlir\include\mlir/StandardOps/Ops.h.inc(473): note: see reference to class template instantiation 'mlir::Op<mlir::ConstantOp,mlir::OpTrait::OneResult,mlir::OpTrait::HasNoSideEffect,mlir::OpTrait::NOperands<0>::Impl>' being compiled
```

Trying to bisect, I get back to 7eb5140a. Not sure how I managed to compile it before.

I am not able to re-open this issue.

**Comment by joker-eph** [comment]
This is strange, we build with VS 2017 I believe @jpienaar / @River707 : any idea?

**Comment by Meinersbur** [comment]
I think I updated the compiler in-between. cl.exe of VS2017 is 19.16.27031.1 for x64.

**Comment by jpienaar** [comment]
We have a change that should fix this on next push.

**Comment by jpienaar** [comment]
@meinersbur could you verify if it the problem has been addressed? Thanks

**Comment by Meinersbur** [comment]
0682b094816eb2b6afbe6630a20bdc15dfbb4649 correctly compiles (and runs check-mlir without fails) with VS2017
