### ISSUE TITLE
Building error,"mlir/IR/OpBase.td"has a problem

### ISSUE THREAD

**Issue by MingliSun** [tensorflow/mlir#322]
[46/450] Building AffineOps.cpp.inc...
FAILED: projects/mlir/include/mlir/Dialect/AffineOps/AffineOps.cpp.inc 
cd /home/sun/llvm-project/build && /home/sun/llvm-project/build/bin/mlir-tblgen -gen-op-defs -I/home/sun/llvm-project/llvm/projects/mlir/include -I/home/sun/llvm-project/build/projects/mlir/include -I /home/sun/llvm-project/llvm/projects/mlir/include/mlir/Dialect/AffineOps -I /home/sun/llvm-project/llvm/include /home/sun/llvm-project/llvm/projects/mlir/include/mlir/Dialect/AffineOps/AffineOps.td --write-if-changed -o projects/mlir/include/mlir/Dialect/AffineOps/AffineOps.cpp.inc -d projects/mlir/include/mlir/Dialect/AffineOps/AffineOps.cpp.inc.d
/home/sun/llvm-project/llvm/projects/mlir/include/mlir/Dialect/AffineOps/AffineOps.td:26:9: error: File '/home/sun/llvm-project/llvm/projects/mlir/include/mlir/IR/OpBase.td' has already been included.
include "mlir/IR/OpBase.td"
        ^
Included from /home/sun/llvm-project/llvm/projects/mlir/include/mlir/Dialect/AffineOps/AffineOps.td:25:
/home/sun/llvm-project/llvm/projects/mlir/include/mlir/Dialect/AffineOps/AffineOpsBase.td:25:9: note: previously included here
include "mlir/IR/OpBase.td"
        ^
/home/sun/llvm-project/llvm/projects/mlir/include/mlir/Dialect/AffineOps/AffineOps.td:26:9: error: Unexpected input at top level
include "mlir/IR/OpBase.td"
        ^
[47/450] Building AffineOps.h.inc...
FAILED: projects/mlir/include/mlir/Dialect/AffineOps/AffineOps.h.inc 
cd /home/sun/llvm-project/build && /home/sun/llvm-project/build/bin/mlir-tblgen -gen-op-decls -I/home/sun/llvm-project/llvm/projects/mlir/include -I/home/sun/llvm-project/build/projects/mlir/include -I /home/sun/llvm-project/llvm/projects/mlir/include/mlir/Dialect/AffineOps -I /home/sun/llvm-project/llvm/include /home/sun/llvm-project/llvm/projects/mlir/include/mlir/Dialect/AffineOps/AffineOps.td --write-if-changed -o projects/mlir/include/mlir/Dialect/AffineOps/AffineOps.h.inc -d projects/mlir/include/mlir/Dialect/AffineOps/AffineOps.h.inc.d
/home/sun/llvm-project/llvm/projects/mlir/include/mlir/Dialect/AffineOps/AffineOps.td:26:9: error: File '/home/sun/llvm-project/llvm/projects/mlir/include/mlir/IR/OpBase.td' has already been included.
include "mlir/IR/OpBase.td"
        ^
Included from /home/sun/llvm-project/llvm/projects/mlir/include/mlir/Dialect/AffineOps/AffineOps.td:25:
/home/sun/llvm-project/llvm/projects/mlir/include/mlir/Dialect/AffineOps/AffineOpsBase.td:25:9: note: previously included here
include "mlir/IR/OpBase.td"
        ^
/home/sun/llvm-project/llvm/projects/mlir/include/mlir/Dialect/AffineOps/AffineOps.td:26:9: error: Unexpected input at top level
include "mlir/IR/OpBase.td"

**Comment by bondhugula** [comment]
Your LLVM copy is behind. These errors will go away on an update to the LLVM trunk. But you'll see other errors that will require this fix: https://github.com/tensorflow/mlir/issues/318

**Comment by MingliSun** [comment]
thank you so much,it worked. And three unexpected test failures occured I post a new issue,"CUDA failed with 700 in StreamSync".I can't solve it.Looking forward to your relay in github.Thank you again.


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Uday Bondhugula"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月15日(星期天) 晚上7:06
收件人:&nbsp;"tensorflow/mlir"<mlir@noreply.github.com&gt;;
抄送:&nbsp;"Madlife"<2239625661@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [tensorflow/mlir] Building error,"mlir/IR/OpBase.td"has a problem (#322)




Your LLVM copy is behind. These errors will go away on an update to the LLVM trunk. But you'll see other errors that will require this fix: #318

**Comment by River707** [comment]
Closing this as it seems you have a separate issue now.
