### ISSUE TITLE
Build failed when following the instructions in README.md

### ISSUE THREAD

**Issue by wyzero** [tensorflow/mlir#326]
env: gcc 9.2, llvm fd7dca98373cee7d379644d6d6e5c163d15107b7

build instructions:
```
cd llvm-project/build
cmake -G Ninja ../llvm -DLLVM_BUILD_EXAMPLES=ON -DLLVM_TARGETS_TO_BUILD="host"
cmake --build . --target check-mlir
```

Errors:
[1518/1734] Building CXX object projects/mlir/lib/Target/CMakeFiles/MLIRTargetNVVMIR.dir/LLVMIR/ConvertToNVVMIR.cpp.o
FAILED: projects/mlir/lib/Target/CMakeFiles/MLIRTargetNVVMIR.dir/LLVMIR/ConvertToNVVMIR.cpp.o
/state/usr/local/bin/g++  -DGTEST_HAS_RTTI=0 -D_DEBUG -D_GNU_SOURCE -D__STDC_CONSTANT_MACROS -D__STDC_FORMAT_MACROS -D__STDC_LIMIT_MACROS -Iprojects/mlir/lib/Target -I/state/dev/xla/features/github/llvm-p
roject-master/llvm/projects/mlir/lib/Target -I/usr/include/libxml2 -Iinclude -I/state/dev/xla/features/github/llvm-project-master/llvm/include -I/state/dev/xla/features/github/llvm-project-master/llvm/pro
jects/mlir/include -Iprojects/mlir/include -fPIC -fvisibility-inlines-hidden -Werror=date-time -Wall -Wextra -Wno-unused-parameter -Wwrite-strings -Wcast-qual -Wno-missing-field-initializers -pedantic -Wn
o-long-long -Wimplicit-fallthrough -Wno-maybe-uninitialized -Wno-class-memaccess -Wno-redundant-move -Wno-noexcept-type -Wdelete-non-virtual-dtor -Wno-comment -fdiagnostics-color -g    -fno-exceptions -fn
o-rtti -std=c++14 -MD -MT projects/mlir/lib/Target/CMakeFiles/MLIRTargetNVVMIR.dir/LLVMIR/ConvertToNVVMIR.cpp.o -MF projects/mlir/lib/Target/CMakeFiles/MLIRTargetNVVMIR.dir/LLVMIR/ConvertToNVVMIR.cpp.o.d
-o projects/mlir/lib/Target/CMakeFiles/MLIRTargetNVVMIR.dir/LLVMIR/ConvertToNVVMIR.cpp.o -c /state/dev/xla/features/github/llvm-project-master/llvm/projects/mlir/lib/Target/LLVMIR/ConvertToNVVMIR.cpp
/state/dev/xla/features/github/llvm-project-master/llvm/projects/mlir/lib/Target/LLVMIR/ConvertToNVVMIR.cpp: In function ‘llvm::Intrinsic::ID {anonymous}::getShflBflyIntrinsicId(llvm::Type*, bool)’:
/state/dev/xla/features/github/llvm-project-master/llvm/projects/mlir/lib/Target/LLVMIR/ConvertToNVVMIR.cpp:51:55: error: ‘nvvm_shfl_sync_bfly_f32p’ is not a member of ‘llvm::Intrinsic’
   51 |     return resultType->isFloatTy() ? llvm::Intrinsic::nvvm_shfl_sync_bfly_f32p
      |                                                       ^~~~~~~~~~~~~~~~~~~~~~~~
/state/dev/xla/features/github/llvm-project-master/llvm/projects/mlir/lib/Target/LLVMIR/ConvertToNVVMIR.cpp:52:55: error: ‘nvvm_shfl_sync_bfly_i32p’ is not a member of ‘llvm::Intrinsic’
   52 |                                    : llvm::Intrinsic::nvvm_shfl_sync_bfly_i32p;
      |                                                       ^~~~~~~~~~~~~~~~~~~~~~~~
/state/dev/xla/features/github/llvm-project-master/llvm/projects/mlir/lib/Target/LLVMIR/ConvertToNVVMIR.cpp:54:53: error: ‘nvvm_shfl_sync_bfly_f32’ is not a member of ‘llvm::Intrinsic’
   54 |   return resultType->isFloatTy() ? llvm::Intrinsic::nvvm_shfl_sync_bfly_f32
      |                                                     ^~~~~~~~~~~~~~~~~~~~~~~
/state/dev/xla/features/github/llvm-project-master/llvm/projects/mlir/lib/Target/LLVMIR/ConvertToNVVMIR.cpp:55:53: error: ‘nvvm_shfl_sync_bfly_i32’ is not a member of ‘llvm::Intrinsic’
   55 |                                  : llvm::Intrinsic::nvvm_shfl_sync_bfly_i32;
      |                                                     ^~~~~~~~~~~~~~~~~~~~~~~

**Comment by joker-eph** [comment]
We're currently broken at the HEAD of LLVM, the current sync'd LLVM is 5bcd34a03ff343674c106b9a6a0406bf249b9b31

**Comment by wyzero** [comment]
Thanks! It works now.
