### ISSUE TITLE
Build stuck with the same warning repeated over and over again

### ISSUE THREAD

**Issue by Aqsa-physics** [tensorflow/mlir#339]
I am building a physics software and at the lst step of my build I am getting the following warning over and over again and the build process is not proceeding forward. This is the warning I am getting 

`In file included from /usr/include/c++/7/cassert:44:0,
                 from src/gsl_utils.hpp:26,
                 from src/root_finder.hpp:33,
                 from src/standard_model.cpp:33:
src/gsl_utils.hpp: In instantiation of ‘void flexiblesusy::copy(const Eigen::DenseBase<Derived>&, gsl_vector*) [with Derived = Eigen::Matrix<double, 1, 1, 0, 1, 1>]’:
src/root_finder.hpp:223:8:   required from ‘static int flexiblesusy::Root_finder<dimension>::gsl_function(const gsl_vector*, void*, gsl_vector*) [with long unsigned int dimension = 1]’
src/root_finder.hpp:139:27:   required from ‘int flexiblesusy::Root_finder<dimension>::find_root(const Vector_t&) [with long unsigned int dimension = 1; flexiblesusy::Root_finder<dimension>::Vector_t = Eigen::Matrix<double, 1, 1, 0, 1, 1>]’
src/root_finder.hpp:263:21:   required from ‘int flexiblesusy::Root_finder<dimension>::solve(const VectorXd&) [with long unsigned int dimension = 1; Eigen::VectorXd = Eigen::Matrix<double, -1, 1>]’
src/standard_model.cpp:4593:1:   required from here
src/gsl_utils.hpp:97:15: warning: comparison between signed and unsigned integer expressions [-Wsign-compare]
    assert(dim == dst->size);
`

This is where my build is stuck with the same above warning repeated over and over.

Any help will be useful. Thank you.

**Comment by joker-eph** [comment]
Hi @Aqsa-physics,

I suspect you posted this in the wrong project? Maybe this is an issue for: https://github.com/FlexibleSUSY/FlexibleSUSY/issues ?
