### ISSUE TITLE
Build configuration with CC=clang CXX=clang fails

### ISSUE THREAD

**Issue by bondhugula** [tensorflow/mlir#35]
This is probably unrelated to the mlir part since clang can't find libstdc++ here. 

CC=clang CXX=clang cmake -G Ninja ../llvm -DLLVM_BUILD_EXAMPLES=ON -DLLVM_ENABLE_CXX1Y=Y -DLLVM_TARGETS_TO_BUILD="host"

ends with this error:

-- Performing Test LLVM_LIBSTDCXX_MIN - Failed
CMake Error at cmake/modules/CheckCompilerVersion.cmake:80 (message):
  libstdc++ version must be at least 4.8.
Call Stack (most recent call first):
  cmake/config-ix.cmake:13 (include)
  CMakeLists.txt:611 (include)

-- Configuring incomplete, errors occurred!
See also "/home/uday/llvm-project/build/CMakeFiles/CMakeOutput.log".
See also "/home/uday/llvm-project/build/CMakeFiles/CMakeError.log".

I do have a recent libstdc++

$ rpm -q libstdc++
libstdc++-9.1.1-1.fc30.x86_64

The error log has:

Performing C++ SOURCE FILE Test LLVM_LIBSTDCXX_MIN failed with the following output:
Change Dir: /home/uday/llvm-project/build/CMakeFiles/CMakeTmp

Run Build Command(s):/usr/bin/ninja-build cmTC_0cf6b 
[1/2] Building CXX object CMakeFiles/cmTC_0cf6b.dir/src.cxx.o
[2/2] Linking CXX executable cmTC_0cf6b
FAILED: cmTC_0cf6b 
: && /usr/lib64/ccache/clang  -DLLVM_LIBSTDCXX_MIN  -std=c++0x   CMakeFiles/cmTC_0cf6b.dir/src.cxx.o  -o cmTC_0cf6b   && :
/usr/bin/ld: CMakeFiles/cmTC_0cf6b.dir/src.cxx.o:(.data+0x0): undefined reference to `std::bad_function_call::what() const'
clang-8: error: linker command failed with exit code 1 (use -v to see invocation)
ninja: build stopped: subcommand failed.

Source file was:

#include <iosfwd>
#if defined(__GLIBCXX__)
#if __GLIBCXX__ < 20130322
#error Unsupported libstdc++ version
#endif
#endif
#if defined(__GLIBCXX__)
extern const char _ZNKSt17bad_function_call4whatEv[];
const char *chk = _ZNKSt17bad_function_call4whatEv;
#else
const char *chk = "";
#endif
int main() { ++chk; return 0; }

$ clang --version
clang version 8.0.0 (Fedora 8.0.0-1.fc30)

**Comment by jpienaar** [comment]
This seems unrelated yes, do you also have the -dev version of library installed? Unfortunately I'm not using fedora so can't repro this. General LLVM mailing list or resources would be able to provide better information here.

Closing as not specific to MLIR.

**Comment by bondhugula** [comment]
Figured out the issue:
.... CXX=clang++ ....  instead of CXX=clang

(clang doesn't link with the C++ std library, although it compiles C++ with the right -std=...

**Comment by bondhugula** [comment]
There was some discussion on this here: http://clang-developers.42468.n3.nabble.com/Re-llvm-dev-New-warnings-when-building-trunk-with-GCC-9-td4062064.html

GCC is using the move ctor for these, while Clang is using the copy ctor; so Clang emits a warning. Using std::move(..) here inverts things - GCC will emit a warning on a redundant std::move while it'd be warning free with Clang. :-(
