### ISSUE TITLE
Add spv.CompositeExtract

### ISSUE THREAD

**Issue by antiagainst** [tensorflow/mlir#42]
The spec for this op is at https://www.khronos.org/registry/spir-v/specs/unified1/SPIRV.html#OpCompositeExtract.

We use Op Definition Spec (ODS) to describe the op, the doc for ODS is here: https://github.com/tensorflow/mlir/blob/master/g3doc/OpDefinitions.md

Useful SPIR-V ODS definitions: https://github.com/tensorflow/mlir/blob/34f7a2d9f8c00f596990ee5385cda2561d8fe202/include/mlir/SPIRV/SPIRVBase.td#L86

It would be nice to define the custom assembly format to look like `std.extract_element`: https://github.com/tensorflow/mlir/blob/34f7a2d9f8c00f596990ee5385cda2561d8fe202/lib/StandardOps/Ops.cpp#L1579-L1594
test: https://github.com/tensorflow/mlir/blob/34f7a2d9f8c00f596990ee5385cda2561d8fe202/test/IR/core-ops.mlir#L357-L368

So for `spv.CompositeExtract`, we will have something like
```
spv.CompositeExtract %composite[%index0, %index1, ...] : <extracted-type>
```

It would be nice to implement the validation rules specified in the op description. You may want to use `spv.struct`, `spv.array` and other types for writing tests.

See the code for adding `spv.Load/spv.Store` as reference: https://github.com/tensorflow/mlir/commit/0c0217d5a76a8a10cc587b6dfd97a40b4d386243

**Comment by antiagainst** [comment]
@denis0x0D is interested in taking this. @denis0x0D, please let me know if you have any questions. :)

**Comment by denis0x0D** [comment]
@antiagainst, I have some thoughts about implementation and your commments, can you please take a look and please fix me if I'm wrong:

1. Seems like the ebnf form should look like this:
```
// <operation> ::= ssa-id `=`  `spv.CompositeExtract` ssa-use
//                 `[` integer-literal (`,` integer-literal)* `]`
//                  `:`  composite-type
```
Regarding to official documentation, the indices are literals and are not in SSA form.
For example:
```
func @composite_extract_2D_array() -> () {
  %0 = spv.Variable : !spv.ptr<!spv.array<4x!spv.array<4xf32>>, Function>
  %1 = spv.Load "Function" %0 ["Volatile"] : !spv.array<4x!spv.array<4xf32>>
  %2 = spv.CompositeExtract %1[1, 2] : !spv.array<4x!spv.array<4xf32>>
  return
}
```

Table-gen description for the indices:
```
...
  let arguments = (ins
    SPV_Composite:$composite,
    ArrayAttr:$indices
  );

  let results = (outs SPV_Type);
...
```

2. The type specified after ":" in ebnf, probably, should be the type of composite object, so in this case we can easaly resolve an operand to an SSA value, but I might miss something, for example code for parser function:

```
   if (parser->parseOperand(compositeInfo) ||
      parser->parseAttribute(indicesAttr, "indices", state->attributes) ||
      parser->parseColon() || parser->parseType(compositeType) ||
      parser->resolveOperand(compositeInfo, compositeType, state->operands)) {
    return failure();
  }
```

3. The result type, regarding to documentation, must be the type of object selected by the last provided index. So, in case of spirv::ArrayType we can get the type of element by getElementType, in case of spirv::StructType we get the type of element by getMemberType, iterating all over the AttrArray of indices.

Thanks.

**Comment by antiagainst** [comment]
1. Yes, ebnf and TableGen looks perfect. You are right regarding the literal indices; they should be embedded as attributes instead of referencing SSA values. (I think we can use `I32ArrayAttr` for `$indices`.) Sorry the example is more for `spv.AccessChain` actually.
2. Yes. Normally it would be nice to trim down the verbosity in the custom assembly form when possible (i.e., by removing duplicated info and scattering the info in a proper way like `spv.Load` and `spv.Store`). But here there is no satisfying way, so using the composite type sounds good.
3. Yes, that's correct.

**Comment by denis0x0D** [comment]
@antiagainst thanks for the answer, it also looks like the StructType should be added to SPV_Type and into CompositeType,

```
def SPV_IsStructType : CPred<"$_self.isa<::mlir::spirv::StructType>()">;
def SPV_AnyStruct : Type<SPV_IsStructType, "any SPIR-V struct type">;
def SPV_Composite: AnyTypeOf<[SPV_Vector, SPV_AnyArray, SPV_AnyStruct]>;
```

As far as I understood this code should be valid, please fix me if I'm wrong, for example:
```
%0 = spv.Variable : !spv.ptr<!spv.struct<f32>, Function>
%1 = spv.Load "Function" %0 ["Volatile"] : !spv.struct<f32>
```
spv assembly 
```
...
%0 = OpVariable %ptrSturctType Function
%1 = OpLoad %StructType %0 Volatile
...
```

and this:
```

  %0 = spv.Variable : !spv.ptr<!spv.struct<f32, !spv.array<4xf32>>, Function>
  %1 = spv.Load "Function" %0 : !spv.struct<f32, !spv.array<4xf32>>
  %2 = spv.CompositeExtract %1[1, 2] : !spv.struct<f32, !spv.array<4xf32>>
```


If it's ok, I will add this alongside with CompositeExtract patch.
Thanks.

**Comment by antiagainst** [comment]
Yep, you are right that struct type should be added to `SPV_Aggregate`, `SPV_Composite` and `SPV_Type`. It is missed in https://github.com/tensorflow/mlir/commit/145112bbbdd4de9ecc9bd17aac6efdf14272337c. Thanks!

**Comment by denis0x0D** [comment]
@antiagainst , ok, thanks! Just a quick question about the typed attributes for indexing, to make sure I understand you in right way. The typed attributes would require to specify the type in code right after the index:
`
 %2 = spv.CompositeExtract %1[1 : i32, 1 :i32] : !spv.struct<f32, !spv.array<4xf32>>
`
in other case of ArrayAttr the code could be:
` %2 = spv.CompositeExtract %1[1, 1] : !spv.struct<f32, !spv.array<4xf32>>`

and inside the parser we can insert a check:

```
for (Attribute subAttr : indexArrayAttr) {
    auto indexAttr = subAttr.dyn_cast<IntegerAttr>();   
     if (!indexAttr) {
    	    parser->emitError(attrLocation, "expexted an array of integer literals");
       return failure();
}
```
Seems like, the second example looks more naturaly, but I can miss a something.
Thanks.

**Comment by antiagainst** [comment]
The default assembly printer  (`ModulePrinter`)  backing `OpAsmPrinter`outputs each attribute's type for uniformity, with a few special cases. For integer attributes, 64-bit cases have their trailing types elided but not 32-bit cases: 
https://github.com/tensorflow/mlir/blob/0682b094816eb2b6afbe6630a20bdc15dfbb4649/lib/IR/AsmPrinter.cpp#L635-L637
I think parsing the second example should be no problem. For printing it that way, it means we cannot use the standard `OpAsmPrinter::printAttribute()`; instead we will need to get the value from the attribute and then stream it to the printer.

For the verification, I think it should happen in the verifier since it is not specific to the parser. (We should only put essential structural checks in the parser to make it able to parse correctly. The majority of validation checks should happen in the verifier.) Although for this case, it will be auto-generated because of `I32ArraryAttr` so it should be okay here. :)

**Comment by denis0x0D** [comment]
@antiagainst got it, thanks!

**Comment by antiagainst** [comment]
Done via #44.
