### ISSUE TITLE
[MLIR:ExecutionEngine] The change in the locking scheme for llvm:orc:ThreadSafeModule causes a build error.

### ISSUE THREAD

**Issue by denis0x0D** [tensorflow/mlir#66]
Hello, recently the locking scheme for ThreadSafeModule was changed alongside with an API
https://reviews.llvm.org/rG809e9d1efa2f58b6333b1a0445e8574beedffc22
, so, at least it causes a build error with llvm on trunk:

```
llvm-project/llvm/projects/mlir/lib/ExecutionEngine/ExecutionEngine.cpp:186:44: error: ‘class llvm::orc::ThreadSafeModule’ has no member named ‘getModule’; did you mean ‘withModuleDo’?
       if (Error err = irTransformer(module.getModule()))
```

it seems like the workarond could be to wrap the code under` #ifdef LLVM_VERSION`, but, I might miss some context in it.
@ftynse I found that "makeIRTransformFunction" was implemented by you, can you please take a look?
Thanks.

**Comment by antiagainst** [comment]
Hey @denis0x0D, thanks for the report! This should be fixed by https://github.com/tensorflow/mlir/commit/3d3d88b2b148714d5357df4fa9c4fc193aacacaf.

**Comment by denis0x0D** [comment]
@antiagainst thanks!
