### ISSUE TITLE
applyPatternsGreedily mutates IR even with empty pattern list

### ISSUE THREAD

**Issue by bondhugula** [tensorflow/mlir#72]
applyPatternsGreedily with an empty pattern list still mutates the IR (I wasn't expecting this). This forces users of the method to write tests that consider the compounded effect (even for parts of the IR that they aren't matching on). This also  means passes performing pattern rewrites in addition to (and after) doing other transformations will have to check for unexpected effects.  Reproduce it for example by running '-canonicalize' after commenting out https://github.com/tensorflow/mlir/blob/fc75bdf86bc784dc034a54705d41273bb1ee387f/lib/Transforms/Canonicalizer.cpp#L50

on this test case:
```
func @test(%arg0: index, %arg1: index, %arg2: index, %arg3: memref<100x200xf32>, %arg4: memref<100x200xf32>) {
  affine.for %arg5 = 0 to %arg0 {
    affine.for %arg6 = 0 to %arg1 {
      %0 = affine.apply (d0) -> (d0)(%arg5)
      %1 = affine.apply (d0) -> (d0)(%arg6)
      "foo"() : () -> ()
      "bar"() : () -> ()
      %2 = affine.load %arg3[%0, %1] : memref<100x200xf32>
    }
  }
  return
}
```

**Comment by joker-eph** [comment]
@River707  hinted me that constant folding is always applied, is this the effect you're referring to here? Do you have an idea about what to do about this?

**Comment by River707** [comment]
Yes, sorry. 'applyPatternsGreedily' also always performs folding/constant folding regardless of whether patterns match or not. It should probably be(it currently isn't) mentioned in the comments.

**Comment by bondhugula** [comment]
In this case, it isn't exactly constant folding (since there are no constants), but just folding. I think besides folding/constant folding, applyPatternsGreedily also always removes dead side effect-free ops irrespective of whether there are any patterns or any patterns match. This is misleading given the name and doc comments, and is probably because the code was originally written to drive the canonicalization pass. While on this, the comment here needs to be fixed as well as it is independent of canonicalization patterns. 

https://github.com/tensorflow/mlir/blob/fc75bdf86bc784dc034a54705d41273bb1ee387f/lib/Transforms/Utils/GreedyPatternRewriteDriver.cpp#L207
