### ISSUE TITLE
[spirv] Extend spv.array with layoutinfo and update serialization

### ISSUE THREAD

**Issue by denis0x0D** [tensorflow/mlir#76]
The spv.array type must be extended with layoutinfo to support decoration:
`OpDecorate %array ArrayStride 4`
Note: this issue is a blocker for https://github.com/tensorflow/mlir/issues/60

**Comment by denis0x0D** [comment]
@antiagainst please let me know if it's ok, if I take this one.
Thanks!

**Comment by antiagainst** [comment]
SGTM, thanks Denis!

**Comment by denis0x0D** [comment]
this is closed by https://github.com/tensorflow/mlir/commit/43cb2e491b095b331659e298f3bb536b29583e56
