### ISSUE TITLE
[spirv] Emit OpCapability for spv.Module serialization

### ISSUE THREAD

**Issue by denis0x0D** [tensorflow/mlir#78]
To generate a valid compute shader the OpCabality is needed.
`OpCapability Shader `
Note: this is a blocker for https://github.com/tensorflow/mlir/issues/60

**Comment by antiagainst** [comment]
https://github.com/tensorflow/mlir/commit/7e719074219050b22c52d6748deedbe6b28b4e9a added support for capability (de)serialization. Closing this.
