### ISSUE TITLE
Build failure - missing std::index_sequence - C++-14 flag missing?

### ISSUE THREAD

**Issue by bondhugula** [tensorflow/mlir#83]
With the current resp. tips of LLVM and MLIR, the build fails with messages below (with both clang and gcc). Looks like the -std=c++14 compile flag is missing from the conf?

In file included from /home/uday/llvm-project-bondhugula/llvm/projects/mlir/lib/TableGen/Argument.cpp:18:
In file included from /home/uday/llvm-project-bondhugula/llvm/projects/mlir/include/mlir/TableGen/Argument.h:33:
In file included from /home/uday/llvm-project-bondhugula/llvm/projects/mlir/include/mlir/TableGen/Attribute.h:27:
In file included from /home/uday/llvm-project-bondhugula/llvm/projects/mlir/include/mlir/TableGen/Constraint.h:28:
In file included from /home/uday/llvm-project-bondhugula/llvm/include/llvm/ADT/StringRef.h:12:
/home/uday/llvm-project-bondhugula/llvm/include/llvm/ADT/STLExtras.h:567:49: error: no template named 'index_sequence' in namespace 'std'
  template <size_t... Ns> value_type deref(std::index_sequence<Ns...>) const {
                                           ~~~~~^
/home/uday/llvm-project-bondhugula/llvm/include/llvm/ADT/STLExtras.h:572:36: error: no template named 'index_sequence' in namespace 'std'
  decltype(iterators) tup_inc(std::index_sequence<Ns...>) const {
                              ~~~~~^
/home/uday/llvm-project-bondhugula/llvm/include/llvm/ADT/STLExtras.h:577:36: error: no template named 'index_sequence' in namespace 'std'
  decltype(iterators) tup_dec

**Comment by denis0x0D** [comment]
@bondhugula this must be fixed by updating CMake https://github.com/tensorflow/mlir/blob/master/CMakeLists.txt#L10
to 14 standard

**Comment by jpienaar** [comment]
Thanks @denis0x0D yes I'll remove that temporary rule given LLVM has changed to using C++14 this week (well the move was planned long in advance, AFAIK the first code using it landed this week).

**Comment by jpienaar** [comment]
Should be addressed by #f8e80e2624623e43f209ac832fd8d3501adfde18. Thanks

**Comment by freedomtan** [comment]
@jpienaar this is another problem. You have to s/llvm::make_unique/std::make_unique/

**Comment by jpienaar** [comment]
@freedomtan yes we have that change pending but we need to wait for another integrate internally before we can submit (there is an ugly workaround I could do in the meantime but I might avoid doing that over the weekend)
